base_url = "https://haysberg.io/"
title = "✨teo@interwebs✨"
description = "SRE mad scientist and funny guy."

compile_sass = true
generate_feeds = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

[markdown.highlighting]
theme = "github-light"

[extra]
author = "Téo Haÿs"
